# Change these first
owner: lelivrescolaire # Your GitHub username
repo: status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: Lelivrescolaire
    slug: lls-front
    url: https://www.lelivrescolaire.fr
    __dangerous__insecure: true
  - name: LLS API
    slug: lls-backend-nodejs
    url: $LLS_API_URL
    __dangerous__insecure: true
  - name: Afterclasse
    slug: afterclasse-front
    url: https://www.afterclasse.fr
    __dangerous__insecure: true
  - name: Afterclasse API
    slug: oklm-nodejs
    url: $AC_API_URL
    __dangerous__insecure: true
  - name: LLS Preprod
    slug: lls-front-dev
    url: $LLS_PREPROD_URL
    __dangerous__insecure: true
  - name: LLS Preprod API
    slug: api-dev
    url: $LLS_PREPROD_API_URL
    __dangerous__insecure: true

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lls.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  apiBaseUrl: https://api.github.com
  logoUrl: https://s3-eu-west-1.amazonaws.com/build.lelivrescolaire.fr/icons/logo.png
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
