# Change these first
owner: lelivrescolaire # Your GitHub username
repo: status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: Lelivrescolaire
    url: https://www.lelivrescolaire.fr
  - name: LLS API
    url: $LLS_API_URL
  - name: Afterclasse
    url: https://www.afterclasse.fr
  - name: Afterclasse API
    url: $AC_API_URL
  - name: LLS Preprod
    url: $LLS_PREPROD_URL
  - name: LLS Preprod API
    url: $LLS_PREPROD_API_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lls.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
